title : Elementary - Jekyll Blog Theme
name: 'Riley Wilson'
description: 'blog'

markdown: kramdown
highlighter: rouge
javascript_enabled: false

featured_posts_title: Unrelated
featured_posts:
  - url: '#'
    title: 'Featured post #1'
  - url: '#'
    title: 'Featured post #2'
  - url: '#'
    title: 'Featured post #3'

collections:
  posts:
    title: Essays
    default_open: true
    output: true

defaults:
  - scope:
      type: posts
    values:
      title: Essays
      permalink: /post/:title


plugins:
  - jekyll-sitemap
